import NominalSets.Wheels
import Mathlib.GroupTheory.Perm.ClosureSwap
import Mathlib.Topology.MetricSpace.Isometry
import Mathlib.Algebra.Group.Subgroup.Pointwise

/-!
# Finite Permutations

A **finite permutation** of a name type `α` is a permutation `π : Equiv.Perm α` that
moves only finitely many atoms, i.e., the set `{a : α | π a ≠ a}` is finite.

Since `α` is infinite (it satisfies `Name α`), we cannot use Mathlib's
`Equiv.Perm.support` (which requires `Fintype`). Instead, we characterise
finite permutations via `Set.Finite` on the complement of `MulAction.fixedBy`.

## Main definitions

* `FinitePerm α` — the subgroup of `Equiv.Perm α` consisting of permutations
  with finite support (finitely many non-fixed points).

## Main results

* `FinitePerm.swap_mem` — every transposition belongs to `FinitePerm α`.
* `FinitePerm.support_finite` — every member has finitely many non-fixed points.
* `FinitePerm.eq_closure_isSwap` — `FinitePerm α` equals the closure of all transpositions.
* `FinitePerm.swap_factorization` — every finite permutation is a product of a finite
  list of transpositions.
-/

open Equiv MulAction Set

namespace Equiv.Perm

variable {α : Type*} (π : Perm α)

/-- The set of atoms moved by a permutation (support already taken by Perm.support) -/
def movedPoints : Set α := {a | π a ≠ a}

/-- A permutation has **finite support** if it moves only finitely many atoms -/
def IsFinitePerm : Prop :=
  π.movedPoints.Finite

theorem movedPoints_eq_compl_fixedBy : π.movedPoints = (fixedBy α π)ᶜ := by
  ext a
  simp [movedPoints, fixedBy, Perm.smul_def]

end Equiv.Perm

/-- `FinitePerm α` is the subgroup of `Equiv.Perm α` consisting of permutations
that move only finitely many atoms. -/
def FinitePerm (α : Type*) : Subgroup (Perm α) where
  carrier := {π | π.IsFinitePerm}
  one_mem' := by
    simp [Equiv.Perm.IsFinitePerm, Equiv.Perm.movedPoints]
  mul_mem' := by
    intro f g hf hg
    simp only [Set.mem_setOf_eq, Equiv.Perm.IsFinitePerm] at *
    apply Set.Finite.subset (hf.union hg)
    intro a ha
    simp only [Equiv.Perm.movedPoints, Set.mem_setOf_eq, Perm.mul_apply] at ha
    by_contra h
    push_neg at h
    obtain ⟨h1, h2⟩ := h
    simp only [Equiv.Perm.movedPoints, Set.mem_setOf_eq, not_not] at h1 h2
    exact ha (by rw [h2, h1])
  inv_mem' := by
    intro f hf
    simp only [Set.mem_setOf_eq, Equiv.Perm.IsFinitePerm, Equiv.Perm.movedPoints] at *
    apply Set.Finite.subset hf
    intro a ha
    simp only [Set.mem_setOf_eq] at *
    intro heq
    rw [← heq, Equiv.Perm.inv_def, Equiv.symm_apply_apply] at ha
    symm at ha
    contradiction

namespace FinitePerm

open Equiv

variable {α : Type*}

/-- Every element of `FinitePerm α` moves finitely many atoms -/
theorem support_finite (π : FinitePerm α) : (π.val.movedPoints).Finite :=
  π.property

/-- Every transposition is a finite permutation (it moves at most 2 atoms) -/
theorem swap_finite (a b : α) [DecidableEq α] : swap a b ∈ FinitePerm α := by
  change (swap a b).IsFinitePerm
  simp only [Perm.IsFinitePerm, Perm.movedPoints]
  apply Set.Finite.subset (({a, b} : Finset α).finite_toSet)
  intro x hx
  simp only [Set.mem_setOf_eq] at hx
  simp only [Finset.mem_coe, Finset.mem_insert, Finset.mem_singleton]
  exact (swap_apply_ne_self_iff.mp hx).2

/-- `FinitePerm α` is exactly the subgroup generated by all transpositions. -/
theorem eq_closure_isSwap [DecidableEq α] :
    FinitePerm α = Subgroup.closure {σ : Perm α | σ.IsSwap} := by
  ext f
  simp only [Subgroup.mem_mk, FinitePerm, Perm.IsFinitePerm, Perm.movedPoints_eq_compl_fixedBy]
  exact mem_closure_isSwap'.symm

/-- Every finite permutation is a product of transpositions: there exists a list of
swaps whose product equals the given permutation. The list may be empty,
in which case the product is the identity by convention. -/
theorem swap_factorization [DecidableEq α] (π : FinitePerm α) :
    ∃ l : List (Perm α), (∀ σ ∈ l, σ.IsSwap) ∧ l.prod = π := by
  obtain ⟨f, hf⟩ := π
  have hmem : f ∈ Subgroup.closure {σ : Perm α | σ.IsSwap} :=
    @eq_closure_isSwap α _ ▸ hf
  induction hmem using Subgroup.closure_induction_left with
  | one => exact ⟨[], by simp, by simp⟩
  | mul_left σ hσ τ hτ ih =>
    obtain ⟨l, hl, hprod⟩ := ih (@eq_closure_isSwap α _ ▸ hτ)
    exact ⟨σ :: l, by simpa [List.forall_mem_cons] using ⟨hσ, hl⟩, by simp [hprod]⟩
  | inv_mul_cancel σ hσ τ hτ ih =>
    obtain ⟨l, hl, hprod⟩ := ih (@eq_closure_isSwap α _ ▸ hτ)
    obtain ⟨x, y, hne, rfl⟩ := hσ
    exact ⟨swap x y :: l, by simpa [List.forall_mem_cons] using ⟨⟨x, y, hne, rfl⟩, hl⟩,
      by simp [Perm.inv_def, hprod]⟩

end FinitePerm
