import Instances.LambdaCalculus.Basic
import Instances.LambdaCalculus.Induction
import Instances.LambdaCalculus.Recursion
import Instances.LambdaCalculus.Substitution
import Instances.LambdaCalculus.Beta
import Instances.LambdaCalculus.Parallel
import Instances.LambdaCalculus.ReductionClosure
