import Instances.LambdaCalculus.Beta
import Mathlib.Logic.Relation

/-!
# Beta Reduction Closures

`Term.BetaStar` is finite, reflexive-transitive beta reduction; `Term.BetaEq` is
beta convertibility, allowing a finite chain of steps in either direction.

These reuse `Relation.ReflTransGen` and `Relation.EqvGen` from the pinned Mathlib
4.34.1 `Mathlib/Logic/Relation.lean`. That API already supplies closure induction,
`ReflTransGen.lift`, `ReflTransGen.lift'`, `ReflTransGen.mono`, and
`EqvGen.reflTransGen_le_eqvGen`. In particular, later comparisons with parallel
reduction can use the existing closure lifting results. No custom closure or
confluence assertion is needed here.

Support containment and freshness preservation hold for directed reduction.
They do not hold for convertibility: reversing an erasing contraction can add
free atoms. Both relations are equivariant and closed under term contexts.
-/

namespace LambdaCalculus

open Nominal.Core Nominal.Set

universe u

variable {α : Type u} [Name α]

namespace Term

/-- Zero or more contextual beta steps. -/
abbrev BetaStar : Term α → Term α → Prop := Relation.ReflTransGen Beta

/-- Beta convertibility: the equivalence relation generated by contextual beta. -/
abbrev BetaEq : Term α → Term α → Prop := Relation.EqvGen Beta

end Term

scoped infix:50 " →β* " => Term.BetaStar
scoped infix:50 " ≡β " => Term.BetaEq

namespace Term

namespace BetaStar

variable {t u v : Term α}

/-- The empty reduction sequence. -/
theorem refl (t : Term α) : t →β* t := Relation.ReflTransGen.refl

/-- A single beta step is a reduction sequence. -/
theorem single (h : Beta t u) : t →β* u := Relation.ReflTransGen.single h

/-- Concatenate two directed reduction sequences. -/
theorem trans (h₁ : t →β* u) (h₂ : u →β* v) : t →β* v :=
  Relation.ReflTransGen.trans h₁ h₂

/-- Reduce the function of an application through any finite sequence. -/
theorem app_left (h : t →β* u) (s : Term α) : app t s →β* app u s :=
  Relation.ReflTransGen.lift (fun t ↦ app t s)
    (fun _ _ h ↦ Beta.app_left h s) _ _ h

/-- Reduce the argument of an application through any finite sequence. -/
theorem app_right (t : Term α) {s s' : Term α} (h : s →β* s') :
    app t s →β* app t s' :=
  Relation.ReflTransGen.lift (app t) (fun _ _ h ↦ Beta.app_right t h) _ _ h

/-- Reduce both parts of an application, in succession. -/
theorem app {t t' s s' : Term α} (ht : t →β* t') (hs : s →β* s') :
    Term.app t s →β* Term.app t' s' :=
  (app_left ht s).trans (app_right t' hs)

/-- Reduce beneath a lambda through any finite sequence. -/
theorem lam (a : α) (h : t →β* u) : Term.lam a t →β* Term.lam a u :=
  Relation.ReflTransGen.lift (Term.lam a) (fun _ _ h ↦ Beta.lam a h) _ _ h

/-- Permute both endpoints of every step in a reduction sequence. -/
theorem equivariant (π : FinitePerm α) (h : t →β* u) : π • t →β* π • u :=
  Relation.ReflTransGen.lift (π • ·) (fun _ _ h ↦ Beta.equivariant π h) _ _ h

/-- Simultaneous permutation preserves and reflects reduction sequences. -/
theorem equivariant_iff (π : FinitePerm α) : (π • t →β* π • u) ↔ (t →β* u) := by
  constructor
  · intro h
    simpa using equivariant π⁻¹ h
  · exact equivariant π

/-- A directed beta sequence introduces no new free atoms. -/
theorem supp_le (h : t →β* u) : supp u ⊆ supp t := by
  induction h with
  | refl => exact Finset.Subset.refl _
  | tail _ h ih => exact (Beta.supp_le h).trans ih

/-- An atom fresh for the source stays fresh through a beta sequence. -/
theorem fresh (h : t →β* u) {a : α} (ha : a # t) : a # u :=
  fresh_of_supp_subset h.supp_le ha

end BetaStar

namespace BetaEq

variable {t u v : Term α}

/-- Every term is beta-convertible with itself. -/
theorem refl (t : Term α) : t ≡β t := Relation.EqvGen.refl t

/-- Convertibility permits reversing a conversion. -/
theorem symm (h : t ≡β u) : u ≡β t := Relation.EqvGen.symm _ _ h

/-- Concatenate conversions. -/
theorem trans (h₁ : t ≡β u) (h₂ : u ≡β v) : t ≡β v :=
  Relation.EqvGen.trans _ _ _ h₁ h₂

/-- A beta step is a conversion. -/
theorem of_beta (h : Beta t u) : t ≡β u := Relation.EqvGen.rel _ _ h

/-- A directed beta sequence is a conversion. -/
theorem of_betaStar (h : t →β* u) : t ≡β u :=
  Relation.EqvGen.reflTransGen_le_eqvGen Beta _ _ h

private theorem map (f : Term α → Term α)
    (hf : ∀ {t u}, Beta t u → Beta (f t) (f u)) (h : t ≡β u) : f t ≡β f u := by
  induction h with
  | rel _ _ h => exact of_beta (hf h)
  | refl t => exact refl (f t)
  | symm _ _ _ ih => exact symm ih
  | trans _ _ _ _ _ ih₁ ih₂ => exact trans ih₁ ih₂

/-- Conversion is preserved in the function position of an application. -/
theorem app_left (h : t ≡β u) (s : Term α) : app t s ≡β app u s :=
  map (fun t ↦ app t s) (fun h ↦ Beta.app_left h s) h

/-- Conversion is preserved in the argument position of an application. -/
theorem app_right (t : Term α) {s s' : Term α} (h : s ≡β s') :
    app t s ≡β app t s' :=
  map (app t) (Beta.app_right t) h

/-- Conversion is preserved beneath a lambda. -/
theorem lam (a : α) (h : t ≡β u) : Term.lam a t ≡β Term.lam a u :=
  map (Term.lam a) (Beta.lam a) h

/-- Permute both endpoints of a conversion. -/
theorem equivariant (π : FinitePerm α) (h : t ≡β u) : π • t ≡β π • u :=
  map (π • ·) (Beta.equivariant π) h

/-- Simultaneous permutation preserves and reflects convertibility. -/
theorem equivariant_iff (π : FinitePerm α) : (π • t ≡β π • u) ↔ (t ≡β u) := by
  constructor
  · intro h
    simpa using equivariant π⁻¹ h
  · exact equivariant π

end BetaEq

end Term

end LambdaCalculus
